[versions]
kotlin        = "1.7.20"
jupiter       = "5.8.2"
antlr         = "4.10.1"

[plugins]
kotlin        = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-gradle      = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlibJdk8  = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"

picocli            = "info.picocli:picocli:4.6.3"

antlr              = { module = "org.antlr:antlr4",         version.ref = "antlr" }
antlr-runtime      = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }

jupiter-params     = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }